# Perform GIS.lab CTU customization

- hosts: all
  become: yes

  vars:
    from_dbname: gismentors
    to_dbname: uzpr
    
  roles:
    - { role: git3, tags: ['git3'] }
    - { role: uzpr, tags: ['uzpr'] }
    - { role: customization-done, tags: ['customization-done'] }
